"""Initial Migration

Revision ID: f8089fe31814
Revises: 
Create Date: 2023-04-12 16:44:43.351137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f8089fe31814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('mtr_user')
    op.drop_constraint('FK__garage__user_id__2B3F6F97', 'garage', type_='foreignkey')
    op.create_foreign_key(None, 'garage', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garage', type_='foreignkey')
    op.create_foreign_key('FK__garage__user_id__2B3F6F97',
                          'garage', 'mtr_user', ['user_id'], ['id'])
    op.create_table('mtr_user',
                    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
                    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='PK__mtr_user__3213E83F2D468AD4')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###
